# Generated by Django 5.0.6 on 2024-06-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Google",
            fields=[
                (
                    "address",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("google_score", models.FloatField()),
                ("num_reviews_google", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "station",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Tabelog",
            fields=[
                (
                    "address",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("menu", models.CharField(max_length=200)),
                ("score", models.FloatField()),
                ("num_reviews", models.IntegerField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_app.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_score", models.FloatField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_app.tabelog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_app.tabelog"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_app.user"
                    ),
                ),
            ],
        ),
    ]
