# Generated by Django 5.0.6 on 2024-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="default_username", max_length=100, unique=True
            ),
        ),
    ]
