# Generated by Django 5.0.6 on 2024-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_alter_user_password_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="city",
            field=models.CharField(default="Tokyo", max_length=100),
        ),
    ]
