# Generated by Django 5.0.6 on 2024-06-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0006_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
